env:
  browser: yes
extends: 'eslint:recommended'
globals:
  Phaser: no
rules:
  indent:
    - 'off'
  linebreak-style:
    - warn
    - unix
  no-console:
    - warn
    - allow:
      - group
      - groupCollapsed
      - groupEnd
      - log
  no-shadow:
    - warn
  no-unused-vars:
    - warn
  quotes:
    - warn
    - double
  semi:
    - warn
    - always
